import React, { createContext, useContext, useState, useEffect } from 'react';
import { additionalTranslations } from './translations';

const LanguageContext = createContext();

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

// Traducciones completas del sistema
const translations = {
  es: {
    // Navegación
    nav: {
      home: 'Inicio',
      events: 'Eventos',
      suppliers: 'Proveedores',
      dashboard: 'Dashboard',
      profile: 'Perfil',
      settings: 'Configuración',
      login: 'Iniciar Sesión',
      register: 'Registrarse',
      logout: 'Cerrar Sesión',
      language: 'Idioma',
      search: 'Buscar',
      searchPlaceholder: 'Buscar eventos, proveedores...',
      notifications: 'Notificaciones',
      menu: 'Menú',
      close: 'Cerrar'
    },
    
    // Autenticación
    auth: {
      login: 'Iniciar Sesión',
      register: 'Registrarse',
      email: 'Correo Electrónico',
      password: 'Contraseña',
      confirmPassword: 'Confirmar Contraseña',
      name: 'Nombre',
      lastName: 'Apellido',
      phone: 'Teléfono',
      rememberMe: 'Recordarme',
      forgotPassword: '¿Olvidaste tu contraseña?',
      noAccount: '¿No tienes cuenta?',
      haveAccount: '¿Ya tienes cuenta?',
      signUpHere: 'Regístrate aquí',
      signInHere: 'Inicia sesión aquí',
      continueWith: 'O continúa con',
      registerWith: 'O regístrate con',
      socialLogin: 'Iniciar sesión con {provider}',
      socialRegister: 'Registrarse con {provider}'
    },
    
    // Eventos
    events: {
      title: 'Eventos',
      subtitle: 'Descubre los mejores eventos de tu ciudad. Filtra, busca y encuentra tu próxima experiencia inolvidable.',
      search: 'Buscar eventos...',
      found: 'encontrado',
      createEvent: 'Crear Evento',
      editEvent: 'Editar Evento',
      deleteEvent: 'Eliminar Evento',
      eventTitle: 'Título del Evento',
      description: 'Descripción',
      date: 'Fecha',
      time: 'Hora',
      location: 'Ubicación',
      price: 'Precio',
      capacity: 'Capacidad',
      category: 'Categoría',
      image: 'Imagen',
      tags: 'Etiquetas',
      status: 'Estado',
      active: 'Activo',
      inactive: 'Inactivo',
      cancelled: 'Cancelado',
      featured: 'Eventos Destacados',
      upcoming: 'Próximos Eventos',
      past: 'Eventos Pasados',
      allEvents: 'Todos los Eventos',
      noEvents: 'No se encontraron eventos',
      noEventsDescription: 'Intenta ajustar los filtros o busca con otros términos.',
      createNewEvent: 'Crear Nuevo Evento',
      eventDetails: 'Detalles del Evento',
      participants: 'Participantes',
      comments: 'Comentarios',
      reviews: 'Reseñas',
      share: 'Compartir',
      save: 'Guardar',
      cancel: 'Cancelar',
      delete: 'Eliminar',
      edit: 'Editar',
      view: 'Ver',
      join: 'Unirse',
      leave: 'Salir',
      full: 'Completo',
      available: 'Disponible',
      soldOut: 'Agotado'
    },
    
    // Proveedores
    suppliers: {
      title: 'Proveedores',
      createSupplier: 'Crear Proveedor',
      editSupplier: 'Editar Proveedor',
      deleteSupplier: 'Eliminar Proveedor',
      supplierName: 'Nombre del Proveedor',
      description: 'Descripción',
      services: 'Servicios',
      rating: 'Calificación',
      reviews: 'Reseñas',
      contact: 'Contacto',
      website: 'Sitio Web',
      socialMedia: 'Redes Sociales',
      portfolio: 'Portfolio',
      availability: 'Disponibilidad',
      pricing: 'Precios',
      experience: 'Experiencia',
      specialties: 'Especialidades',
      noSuppliers: 'No hay proveedores disponibles',
      createNewSupplier: 'Crear Nuevo Proveedor',
      supplierDetails: 'Detalles del Proveedor',
      contactSupplier: 'Contactar Proveedor',
      hireSupplier: 'Contratar Proveedor',
      viewPortfolio: 'Ver Portfolio',
      addReview: 'Agregar Reseña',
      editReview: 'Editar Reseña',
      deleteReview: 'Eliminar Reseña'
    },
    
    // Dashboard
    dashboard: {
      title: 'Dashboard',
      welcome: 'Bienvenido',
      subtitle: 'Gestiona tus eventos y proveedores desde aquí',
      totalEvents: 'Total de Eventos',
      totalUsers: 'Total de Usuarios',
      totalRevenue: 'Ingresos Totales',
      activeEvents: 'Eventos Activos',
      thisMonth: 'Este Mes',
      activeUsers: 'Usuarios Activos',
      ongoing: 'En Curso',
      recentActivity: 'Actividad Reciente',
      upcomingEvents: 'Próximos Eventos',
      viewAll: 'Ver Todo',
      refresh: 'Actualizar',
      filter: 'Filtrar',
      download: 'Descargar',
      share: 'Compartir',
      stats: 'Estadísticas',
      analytics: 'Análisis',
      reports: 'Reportes',
      settings: 'Configuración'
    },
    
    // Formularios
    forms: {
      required: 'Campo requerido',
      invalidEmail: 'Email inválido',
      passwordTooShort: 'La contraseña debe tener al menos 8 caracteres',
      passwordsDoNotMatch: 'Las contraseñas no coinciden',
      invalidPhone: 'Número de teléfono inválido',
      invalidDate: 'Fecha inválida',
      invalidTime: 'Hora inválida',
      invalidPrice: 'Precio inválido',
      invalidCapacity: 'Capacidad inválida',
      fileTooLarge: 'El archivo es demasiado grande',
      invalidFileType: 'Tipo de archivo no válido',
      maxLength: 'Máximo {max} caracteres',
      minLength: 'Mínimo {min} caracteres',
      selectOption: 'Selecciona una opción',
      uploadFile: 'Subir archivo',
      dragAndDrop: 'Arrastra y suelta archivos aquí',
      or: 'o',
      browse: 'Examinar',
      remove: 'Eliminar',
      save: 'Guardar',
      cancel: 'Cancelar',
      submit: 'Enviar',
      reset: 'Limpiar',
      loading: 'Cargando...',
      saving: 'Guardando...',
      success: '¡Éxito!',
      error: 'Error',
      warning: 'Advertencia',
      info: 'Información'
    },
    
    // Mensajes del sistema
    messages: {
      success: {
        eventCreated: 'Evento creado exitosamente',
        eventUpdated: 'Evento actualizado exitosamente',
        eventDeleted: 'Evento eliminado exitosamente',
        supplierCreated: 'Proveedor creado exitosamente',
        supplierUpdated: 'Proveedor actualizado exitosamente',
        supplierDeleted: 'Proveedor eliminado exitosamente',
        userRegistered: 'Usuario registrado exitosamente',
        userLoggedIn: 'Usuario inició sesión exitosamente',
        userLoggedOut: 'Usuario cerró sesión exitosamente',
        profileUpdated: 'Perfil actualizado exitosamente',
        settingsSaved: 'Configuración guardada exitosamente',
        dataSaved: 'Datos guardados exitosamente'
      },
      error: {
        generic: 'Ha ocurrido un error inesperado',
        network: 'Error de conexión. Verifica tu internet.',
        unauthorized: 'No tienes permisos para realizar esta acción',
        forbidden: 'Acceso denegado',
        notFound: 'Recurso no encontrado',
        validation: 'Datos de entrada inválidos',
        server: 'Error interno del servidor',
        loginFailed: 'Credenciales inválidas',
        registrationFailed: 'Error al registrar usuario',
        eventNotFound: 'Evento no encontrado',
        supplierNotFound: 'Proveedor no encontrado',
        userNotFound: 'Usuario no encontrado',
        fileUploadFailed: 'Error al subir archivo',
        paymentFailed: 'Error en el pago',
        emailSendFailed: 'Error al enviar email'
      },
      warning: {
        unsavedChanges: 'Tienes cambios sin guardar',
        confirmDelete: '¿Estás seguro de que quieres eliminar este elemento?',
        sessionExpired: 'Tu sesión ha expirado',
        lowStorage: 'Espacio de almacenamiento bajo',
        maintenanceMode: 'El sistema está en modo mantenimiento'
      },
      info: {
        loading: 'Cargando...',
        noData: 'No hay datos disponibles',
        searchResults: 'Resultados de búsqueda',
        filtersApplied: 'Filtros aplicados',
        dataUpdated: 'Datos actualizados',
        newVersionAvailable: 'Nueva versión disponible'
      }
    },
    
    // Categorías de eventos
    categories: {
      concert: 'Concierto',
      conference: 'Conferencia',
      workshop: 'Workshop',
      sport: 'Deporte',
      art: 'Arte',
      technology: 'Tecnología',
      business: 'Negocios',
      other: 'Otro'
    },
    
    // Estados
    status: {
      active: 'Activo',
      inactive: 'Inactivo',
      pending: 'Pendiente',
      approved: 'Aprobado',
      rejected: 'Rechazado',
      cancelled: 'Cancelado',
      completed: 'Completado',
      draft: 'Borrador',
      published: 'Publicado'
    },
    
    // Roles
    roles: {
      admin: 'Administrador',
      user: 'Usuario',
      supplier: 'Proveedor',
      moderator: 'Moderador'
    },
    
    // Fechas y tiempo
    time: {
      now: 'Ahora',
      today: 'Hoy',
      yesterday: 'Ayer',
      tomorrow: 'Mañana',
      thisWeek: 'Esta Semana',
      thisMonth: 'Este Mes',
      thisYear: 'Este Año',
      lastWeek: 'Semana Pasada',
      lastMonth: 'Mes Pasado',
      lastYear: 'Año Pasado',
      nextWeek: 'Próxima Semana',
      nextMonth: 'Próximo Mes',
      nextYear: 'Próximo Año',
      monday: 'Lunes',
      tuesday: 'Martes',
      wednesday: 'Miércoles',
      thursday: 'Jueves',
      friday: 'Viernes',
      saturday: 'Sábado',
      sunday: 'Domingo',
      january: 'Enero',
      february: 'Febrero',
      march: 'Marzo',
      april: 'Abril',
      may: 'Mayo',
      june: 'Junio',
      july: 'Julio',
      august: 'Agosto',
      september: 'Septiembre',
      october: 'Octubre',
      november: 'Noviembre',
      december: 'Diciembre'
    },
    
    // Configuración
    settings: {
      title: 'Configuración',
      general: 'General',
      profile: 'Perfil',
      notifications: 'Notificaciones',
      privacy: 'Privacidad',
      security: 'Seguridad',
      language: 'Idioma',
      theme: 'Tema',
      timezone: 'Zona Horaria',
      currency: 'Moneda',
      dateFormat: 'Formato de Fecha',
      timeFormat: 'Formato de Hora',
      emailNotifications: 'Notificaciones por Email',
      pushNotifications: 'Notificaciones Push',
      smsNotifications: 'Notificaciones SMS',
      profileVisibility: 'Visibilidad del Perfil',
      showEmail: 'Mostrar Email',
      showPhone: 'Mostrar Teléfono',
      public: 'Público',
      private: 'Privado',
      friends: 'Amigos',
      save: 'Guardar',
      cancel: 'Cancelar',
      reset: 'Restablecer',
      delete: 'Eliminar'
    },
    
    // Páginas principales
    pages: {
      home: {
        title: 'Inicio',
        subtitle: 'Descubre los mejores eventos de tu ciudad',
        featuredEvents: 'Eventos Destacados',
        upcomingEvents: 'Próximos Eventos',
        categories: 'Categorías',
        whyChooseUs: '¿Por qué elegir MainEvents?',
        testimonials: 'Testimonios',
        stats: 'Estadísticas',
        joinNow: 'Únete Ahora',
        learnMore: 'Saber Más'
      },
      about: {
        title: 'Acerca de Nosotros',
        mission: 'Nuestra Misión',
        vision: 'Nuestra Visión',
        team: 'Nuestro Equipo',
        values: 'Nuestros Valores'
      },
      contact: {
        title: 'Contacto',
        getInTouch: 'Ponte en Contacto',
        name: 'Nombre',
        email: 'Correo Electrónico',
        subject: 'Asunto',
        message: 'Mensaje',
        send: 'Enviar',
        address: 'Dirección',
        phone: 'Teléfono',
        hours: 'Horarios de Atención'
      },
      help: {
        title: 'Ayuda',
        faq: 'Preguntas Frecuentes',
        support: 'Soporte',
        documentation: 'Documentación',
        tutorials: 'Tutoriales'
      }
    },
    
    // Formularios específicos
    forms: {
      createEvent: {
        title: 'Crear Evento',
        basicInfo: 'Información Básica',
        eventDetails: 'Detalles del Evento',
        pricing: 'Precios y Capacidad',
        media: 'Imágenes y Multimedia',
        settings: 'Configuración',
        publish: 'Publicar Evento',
        saveDraft: 'Guardar Borrador',
        preview: 'Vista Previa'
      },
      editProfile: {
        title: 'Editar Perfil',
        personalInfo: 'Información Personal',
        contactInfo: 'Información de Contacto',
        preferences: 'Preferencias',
        security: 'Seguridad',
        socialAccounts: 'Cuentas Sociales'
      },
      payment: {
        title: 'Procesar Pago',
        paymentMethod: 'Método de Pago',
        billingInfo: 'Información de Facturación',
        summary: 'Resumen del Pedido',
        total: 'Total',
        processPayment: 'Procesar Pago',
        cancel: 'Cancelar'
      }
    },
    
    // Estados y validaciones
    validation: {
      required: 'Este campo es requerido',
      email: 'Ingresa un email válido',
      minLength: 'Mínimo {min} caracteres',
      maxLength: 'Máximo {max} caracteres',
      password: 'La contraseña debe tener al menos 8 caracteres',
      confirmPassword: 'Las contraseñas deben coincidir',
      phone: 'Ingresa un número de teléfono válido',
      url: 'Ingresa una URL válida',
      date: 'Ingresa una fecha válida',
      time: 'Ingresa una hora válida',
      number: 'Ingresa un número válido',
      positive: 'El número debe ser positivo',
      future: 'La fecha debe ser futura',
      past: 'La fecha debe ser pasada'
    },
    
    // Acciones comunes
    actions: {
      add: 'Agregar',
      edit: 'Editar',
      delete: 'Eliminar',
      save: 'Guardar',
      cancel: 'Cancelar',
      confirm: 'Confirmar',
      close: 'Cerrar',
      open: 'Abrir',
      view: 'Ver',
      download: 'Descargar',
      upload: 'Subir',
      search: 'Buscar',
      filter: 'Filtrar',
      sort: 'Ordenar',
      refresh: 'Actualizar',
      reload: 'Recargar',
      back: 'Atrás',
      next: 'Siguiente',
      previous: 'Anterior',
      finish: 'Finalizar',
      submit: 'Enviar',
      reset: 'Limpiar',
      clear: 'Borrar',
      select: 'Seleccionar',
      deselect: 'Deseleccionar',
      selectAll: 'Seleccionar Todo',
      deselectAll: 'Deseleccionar Todo',
      enable: 'Habilitar',
      disable: 'Deshabilitar',
      activate: 'Activar',
      deactivate: 'Desactivar',
      publish: 'Publicar',
      unpublish: 'Despublicar',
      approve: 'Aprobar',
      reject: 'Rechazar',
      accept: 'Aceptar',
      decline: 'Declinar',
      invite: 'Invitar',
      join: 'Unirse',
      leave: 'Salir',
      follow: 'Seguir',
      unfollow: 'Dejar de Seguir',
      like: 'Me Gusta',
      unlike: 'No Me Gusta',
      share: 'Compartir',
      copy: 'Copiar',
      paste: 'Pegar',
      cut: 'Cortar',
      undo: 'Deshacer',
      redo: 'Rehacer',
      print: 'Imprimir',
      export: 'Exportar',
      import: 'Importar',
      sync: 'Sincronizar',
      backup: 'Respaldo',
      restore: 'Restaurar',
      archive: 'Archivar',
      unarchive: 'Desarchivar',
      duplicate: 'Duplicar',
      move: 'Mover',
      copy: 'Copiar',
      rename: 'Renombrar',
      create: 'Crear',
      update: 'Actualizar',
      remove: 'Remover',
      clear: 'Limpiar',
      reset: 'Restablecer',
      refresh: 'Actualizar',
      reload: 'Recargar',
      retry: 'Reintentar',
      continue: 'Continuar',
      skip: 'Omitir',
      complete: 'Completar',
      finish: 'Terminar',
      start: 'Iniciar',
      stop: 'Detener',
      pause: 'Pausar',
      resume: 'Reanudar',
      play: 'Reproducir',
      pause: 'Pausar',
      stop: 'Detener',
      mute: 'Silenciar',
      unmute: 'Activar Sonido',
      fullscreen: 'Pantalla Completa',
      exitFullscreen: 'Salir de Pantalla Completa',
      zoomIn: 'Acercar',
      zoomOut: 'Alejar',
      fit: 'Ajustar',
      rotate: 'Rotar',
      flip: 'Voltear',
      crop: 'Recortar',
      resize: 'Redimensionar',
      compress: 'Comprimir',
      extract: 'Extraer',
      encrypt: 'Encriptar',
      decrypt: 'Desencriptar',
      lock: 'Bloquear',
      unlock: 'Desbloquear',
      hide: 'Ocultar',
      show: 'Mostrar',
      expand: 'Expandir',
      collapse: 'Contraer',
      maximize: 'Maximizar',
      minimize: 'Minimizar',
      restore: 'Restaurar',
      close: 'Cerrar',
      open: 'Abrir',
      new: 'Nuevo',
      old: 'Viejo',
      recent: 'Reciente',
      popular: 'Popular',
      trending: 'Tendencia',
      featured: 'Destacado',
      recommended: 'Recomendado',
      suggested: 'Sugerido',
      related: 'Relacionado',
      similar: 'Similar',
      other: 'Otro',
      all: 'Todos',
      none: 'Ninguno',
      some: 'Algunos',
      many: 'Muchos',
      few: 'Pocos',
      more: 'Más',
      less: 'Menos',
      most: 'La Mayoría',
      least: 'El Menor',
      best: 'Mejor',
      worst: 'Peor',
      better: 'Mejor',
      worse: 'Peor',
      good: 'Bueno',
      bad: 'Malo',
      great: 'Excelente',
      terrible: 'Terrible',
      awesome: 'Increíble',
      amazing: 'Asombroso',
      wonderful: 'Maravilloso',
      fantastic: 'Fantástico',
      perfect: 'Perfecto',
      excellent: 'Excelente',
      outstanding: 'Sobresaliente',
      remarkable: 'Notable',
      impressive: 'Impresionante',
      incredible: 'Increíble',
      unbelievable: 'Increíble',
      extraordinary: 'Extraordinario',
      exceptional: 'Excepcional',
      magnificent: 'Magnífico',
      splendid: 'Espléndido',
      superb: 'Excelente',
      terrific: 'Fantástico',
      fabulous: 'Fabuloso',
      marvelous: 'Maravilloso',
      brilliant: 'Brillante',
      outstanding: 'Sobresaliente',
      remarkable: 'Notable',
      impressive: 'Impresionante',
      incredible: 'Increíble',
      unbelievable: 'Increíble',
      extraordinary: 'Extraordinario',
      exceptional: 'Excepcional',
      magnificent: 'Magnífico',
      splendid: 'Espléndido',
      superb: 'Excelente',
      terrific: 'Fantástico',
      fabulous: 'Fabuloso',
      marvelous: 'Maravilloso',
      brilliant: 'Brillante'
    },
    
    // Tiempo y fechas
    time: {
      now: 'Ahora',
      today: 'Hoy',
      yesterday: 'Ayer',
      tomorrow: 'Mañana',
      thisWeek: 'Esta Semana',
      thisMonth: 'Este Mes',
      thisYear: 'Este Año',
      lastWeek: 'Semana Pasada',
      lastMonth: 'Mes Pasado',
      lastYear: 'Año Pasado',
      nextWeek: 'Próxima Semana',
      nextMonth: 'Próximo Mes',
      nextYear: 'Próximo Año',
      monday: 'Lunes',
      tuesday: 'Martes',
      wednesday: 'Miércoles',
      thursday: 'Jueves',
      friday: 'Viernes',
      saturday: 'Sábado',
      sunday: 'Domingo',
      january: 'Enero',
      february: 'Febrero',
      march: 'Marzo',
      april: 'Abril',
      may: 'Mayo',
      june: 'Junio',
      july: 'Julio',
      august: 'Agosto',
      september: 'Septiembre',
      october: 'Octubre',
      november: 'Noviembre',
      december: 'Diciembre',
      morning: 'Mañana',
      afternoon: 'Tarde',
      evening: 'Noche',
      night: 'Noche',
      dawn: 'Madrugada',
      noon: 'Mediodía',
      midnight: 'Medianoche',
      am: 'AM',
      pm: 'PM',
      second: 'Segundo',
      minute: 'Minuto',
      hour: 'Hora',
      day: 'Día',
      week: 'Semana',
      month: 'Mes',
      year: 'Año',
      decade: 'Década',
      century: 'Siglo',
      millennium: 'Milenio',
      ago: 'Hace',
      in: 'En',
      at: 'A las',
      on: 'El',
      from: 'Desde',
      to: 'Hasta',
      until: 'Hasta',
      since: 'Desde',
      before: 'Antes',
      after: 'Después',
      during: 'Durante',
      while: 'Mientras',
      when: 'Cuando',
      then: 'Entonces',
      now: 'Ahora',
      later: 'Más tarde',
      earlier: 'Más temprano',
      soon: 'Pronto',
      recently: 'Recientemente',
      lately: 'Últimamente',
      currently: 'Actualmente',
      presently: 'Actualmente',
      immediately: 'Inmediatamente',
      instantly: 'Instantáneamente',
      quickly: 'Rápidamente',
      slowly: 'Lentamente',
      fast: 'Rápido',
      slow: 'Lento',
      early: 'Temprano',
      late: 'Tarde',
      onTime: 'A tiempo',
      punctual: 'Puntual',
      delayed: 'Retrasado',
      overdue: 'Vencido',
      expired: 'Expirado',
      valid: 'Válido',
      invalid: 'Inválido',
      active: 'Activo',
      inactive: 'Inactivo',
      pending: 'Pendiente',
      completed: 'Completado',
      cancelled: 'Cancelado',
      scheduled: 'Programado',
      ongoing: 'En curso',
      finished: 'Terminado',
      started: 'Iniciado',
      stopped: 'Detenido',
      paused: 'Pausado',
      resumed: 'Reanudado',
      created: 'Creado',
      updated: 'Actualizado',
      deleted: 'Eliminado',
      restored: 'Restaurado',
      archived: 'Archivado',
      unarchived: 'Desarchivado',
      published: 'Publicado',
      unpublished: 'Despublicado',
      approved: 'Aprobado',
      rejected: 'Rechazado',
      accepted: 'Aceptado',
      declined: 'Declinado',
      confirmed: 'Confirmado',
      unconfirmed: 'Sin confirmar',
      verified: 'Verificado',
      unverified: 'Sin verificar',
      authenticated: 'Autenticado',
      unauthenticated: 'Sin autenticar',
      authorized: 'Autorizado',
      unauthorized: 'No autorizado',
      enabled: 'Habilitado',
      disabled: 'Deshabilitado',
      visible: 'Visible',
      hidden: 'Oculto',
      public: 'Público',
      private: 'Privado',
      shared: 'Compartido',
      unshared: 'No compartido',
      locked: 'Bloqueado',
      unlocked: 'Desbloqueado',
      open: 'Abierto',
      closed: 'Cerrado',
      available: 'Disponible',
      unavailable: 'No disponible',
      online: 'En línea',
      offline: 'Fuera de línea',
      connected: 'Conectado',
      disconnected: 'Desconectado',
      synced: 'Sincronizado',
      unsynced: 'Sin sincronizar',
      backedUp: 'Respaldado',
      notBackedUp: 'Sin respaldo',
      restored: 'Restaurado',
      notRestored: 'Sin restaurar',
      imported: 'Importado',
      exported: 'Exportado',
      downloaded: 'Descargado',
      uploaded: 'Subido',
      sent: 'Enviado',
      received: 'Recibido',
      delivered: 'Entregado',
      undelivered: 'No entregado',
      read: 'Leído',
      unread: 'No leído',
      seen: 'Visto',
      unseen: 'No visto',
      viewed: 'Visualizado',
      notViewed: 'No visualizado',
      clicked: 'Clickeado',
      notClicked: 'No clickeado',
      opened: 'Abierto',
      notOpened: 'No abierto',
      closed: 'Cerrado',
      notClosed: 'No cerrado',
      started: 'Iniciado',
      notStarted: 'No iniciado',
      finished: 'Terminado',
      notFinished: 'No terminado',
      completed: 'Completado',
      notCompleted: 'No completado',
      successful: 'Exitoso',
      unsuccessful: 'No exitoso',
      failed: 'Fallido',
      passed: 'Aprobado',
      failed: 'Reprobado',
      won: 'Ganado',
      lost: 'Perdido',
      tied: 'Empatado',
      drawn: 'Empatado',
      default: 'Por defecto',
      custom: 'Personalizado',
      standard: 'Estándar',
      premium: 'Premium',
      basic: 'Básico',
      advanced: 'Avanzado',
      pro: 'Pro',
      enterprise: 'Empresarial',
      free: 'Gratis',
      paid: 'De pago',
      trial: 'Prueba',
      demo: 'Demo',
      beta: 'Beta',
      alpha: 'Alpha',
      stable: 'Estable',
      unstable: 'Inestable',
      experimental: 'Experimental',
      deprecated: 'Obsoleto',
      legacy: 'Legacy',
      modern: 'Moderno',
      classic: 'Clásico',
      new: 'Nuevo',
      old: 'Viejo',
      latest: 'Más reciente',
      oldest: 'Más antiguo',
      first: 'Primero',
      last: 'Último',
      next: 'Siguiente',
      previous: 'Anterior',
      current: 'Actual',
      future: 'Futuro',
      past: 'Pasado',
      present: 'Presente',
      recent: 'Reciente',
      ancient: 'Antiguo',
      fresh: 'Fresco',
      stale: 'Viejo',
      new: 'Nuevo',
      used: 'Usado',
      secondHand: 'Segunda mano',
      refurbished: 'Reacondicionado',
      original: 'Original',
      copy: 'Copia',
      duplicate: 'Duplicado',
      fake: 'Falso',
      real: 'Real',
      genuine: 'Genuino',
      authentic: 'Auténtico',
      legitimate: 'Legítimo',
      legal: 'Legal',
      illegal: 'Ilegal',
      valid: 'Válido',
      invalid: 'Inválido',
      correct: 'Correcto',
      incorrect: 'Incorrecto',
      right: 'Correcto',
      wrong: 'Incorrecto',
      true: 'Verdadero',
      false: 'Falso',
      yes: 'Sí',
      no: 'No',
      maybe: 'Tal vez',
      perhaps: 'Quizás',
      possibly: 'Posiblemente',
      probably: 'Probablemente',
      definitely: 'Definitivamente',
      certainly: 'Ciertamente',
      absolutely: 'Absolutamente',
      never: 'Nunca',
      always: 'Siempre',
      sometimes: 'A veces',
      often: 'A menudo',
      rarely: 'Raramente',
      frequently: 'Frecuentemente',
      occasionally: 'Ocasionalmente',
      regularly: 'Regularmente',
      irregularly: 'Irregularmente',
      constantly: 'Constantemente',
      continuously: 'Continuamente',
      intermittently: 'Intermitentemente',
      sporadically: 'Esporádicamente',
      periodically: 'Periódicamente',
      daily: 'Diariamente',
      weekly: 'Semanalmente',
      monthly: 'Mensualmente',
      yearly: 'Anualmente',
      hourly: 'Cada hora',
      minutely: 'Cada minuto',
      secondly: 'Cada segundo',
      instantly: 'Instantáneamente',
      immediately: 'Inmediatamente',
      quickly: 'Rápidamente',
      slowly: 'Lentamente',
      fast: 'Rápido',
      slow: 'Lento',
      rapid: 'Rápido',
      gradual: 'Gradual',
      sudden: 'Repentino',
      abrupt: 'Abrupto',
      smooth: 'Suave',
      rough: 'Áspero',
      gentle: 'Suave',
      harsh: 'Duro',
      soft: 'Suave',
      hard: 'Duro',
      easy: 'Fácil',
      difficult: 'Difícil',
      simple: 'Simple',
      complex: 'Complejo',
      basic: 'Básico',
      advanced: 'Avanzado',
      beginner: 'Principiante',
      intermediate: 'Intermedio',
      expert: 'Experto',
      professional: 'Profesional',
      amateur: 'Aficionado',
      novice: 'Novato',
      veteran: 'Veterano',
      experienced: 'Experimentado',
      inexperienced: 'Inexperto',
      skilled: 'Hábil',
      unskilled: 'No hábil',
      talented: 'Talentoso',
      untalented: 'Sin talento',
      gifted: 'Dotado',
      ungifted: 'Sin dones',
      intelligent: 'Inteligente',
      unintelligent: 'No inteligente',
      smart: 'Inteligente',
      stupid: 'Estúpido',
      wise: 'Sabio',
      foolish: 'Tonto',
      clever: 'Astuto',
      dull: 'Tonto',
      bright: 'Brillante',
      dim: 'Oscuro',
      sharp: 'Agudo',
      blunt: 'Desafilado',
      keen: 'Agudo',
      obtuse: 'Obtuso',
      acute: 'Agudo',
      chronic: 'Crónico',
      temporary: 'Temporal',
      permanent: 'Permanente',
      lasting: 'Duradero',
      fleeting: 'Fugaz',
      brief: 'Breve',
      lengthy: 'Largo',
      short: 'Corto',
      long: 'Largo',
      tall: 'Alto',
      short: 'Bajo',
      high: 'Alto',
      low: 'Bajo',
      deep: 'Profundo',
      shallow: 'Poco profundo',
      wide: 'Ancho',
      narrow: 'Estrecho',
      broad: 'Amplio',
      thin: 'Delgado',
      thick: 'Grueso',
      fat: 'Gordo',
      slim: 'Delgado',
      skinny: 'Flaco',
      overweight: 'Sobrepeso',
      underweight: 'Bajo peso',
      heavy: 'Pesado',
      light: 'Ligero',
      strong: 'Fuerte',
      weak: 'Débil',
      powerful: 'Poderoso',
      powerless: 'Sin poder',
      mighty: 'Poderoso',
      feeble: 'Débil',
      robust: 'Robusto',
      fragile: 'Frágil',
      sturdy: 'Robusto',
      delicate: 'Delicado',
      tough: 'Duro',
      tender: 'Tierno',
      rough: 'Áspero',
      smooth: 'Suave',
      coarse: 'Grueso',
      fine: 'Fino',
      gross: 'Bruto',
      net: 'Neto',
      total: 'Total',
      partial: 'Parcial',
      complete: 'Completo',
      incomplete: 'Incompleto',
      whole: 'Entero',
      half: 'Mitad',
      quarter: 'Cuarto',
      third: 'Tercero',
      double: 'Doble',
      triple: 'Triple',
      single: 'Solo',
      multiple: 'Múltiple',
      many: 'Muchos',
      few: 'Pocos',
      several: 'Varios',
      numerous: 'Numerosos',
      countless: 'Innumerables',
      infinite: 'Infinito',
      finite: 'Finito',
      limited: 'Limitado',
      unlimited: 'Ilimitado',
      restricted: 'Restringido',
      unrestricted: 'Sin restricciones',
      free: 'Libre',
      bound: 'Atado',
      tied: 'Atado',
      loose: 'Suelto',
      tight: 'Apretado',
      secure: 'Seguro',
      insecure: 'Inseguro',
      safe: 'Seguro',
      dangerous: 'Peligroso',
      risky: 'Arriesgado',
      hazardous: 'Peligroso',
      harmful: 'Dañino',
      harmless: 'Inofensivo',
      beneficial: 'Beneficioso',
      useful: 'Útil',
      useless: 'Inútil',
      helpful: 'Útil',
      unhelpful: 'No útil',
      valuable: 'Valioso',
      worthless: 'Sin valor',
      precious: 'Precioso',
      cheap: 'Barato',
      expensive: 'Caro',
      costly: 'Costoso',
      affordable: 'Asequible',
      reasonable: 'Razonable',
      unreasonable: 'Irrazonable',
      fair: 'Justo',
      unfair: 'Injusto',
      just: 'Justo',
      unjust: 'Injusto',
      right: 'Correcto',
      wrong: 'Incorrecto',
      good: 'Bueno',
      bad: 'Malo',
      better: 'Mejor',
      worse: 'Peor',
      best: 'Mejor',
      worst: 'Peor',
      great: 'Excelente',
      terrible: 'Terrible',
      awesome: 'Increíble',
      amazing: 'Asombroso',
      wonderful: 'Maravilloso',
      fantastic: 'Fantástico',
      perfect: 'Perfecto',
      excellent: 'Excelente',
      outstanding: 'Sobresaliente',
      remarkable: 'Notable',
      impressive: 'Impresionante',
      incredible: 'Increíble',
      unbelievable: 'Increíble',
      extraordinary: 'Extraordinario',
      exceptional: 'Excepcional',
      magnificent: 'Magnífico',
      splendid: 'Espléndido',
      superb: 'Excelente',
      terrific: 'Fantástico',
      fabulous: 'Fabuloso',
      marvelous: 'Maravilloso',
      brilliant: 'Brillante',
      outstanding: 'Sobresaliente',
      remarkable: 'Notable',
      impressive: 'Impresionante',
      incredible: 'Increíble',
      unbelievable: 'Increíble',
      extraordinary: 'Extraordinario',
      exceptional: 'Excepcional',
      magnificent: 'Magnífico',
      splendid: 'Espléndido',
      superb: 'Excelente',
      terrific: 'Fantástico',
      fabulous: 'Fabuloso',
      marvelous: 'Maravilloso',
      brilliant: 'Brillante'
    }
  },
  
  en: {
    // Navigation
    nav: {
      home: 'Home',
      events: 'Events',
      suppliers: 'Suppliers',
      dashboard: 'Dashboard',
      profile: 'Profile',
      settings: 'Settings',
      login: 'Login',
      register: 'Register',
      logout: 'Logout',
      language: 'Language',
      search: 'Search',
      searchPlaceholder: 'Search events, suppliers...',
      notifications: 'Notifications',
      menu: 'Menu',
      close: 'Close'
    },
    
    // Authentication
    auth: {
      login: 'Login',
      register: 'Register',
      email: 'Email',
      password: 'Password',
      confirmPassword: 'Confirm Password',
      name: 'Name',
      lastName: 'Last Name',
      phone: 'Phone',
      rememberMe: 'Remember Me',
      forgotPassword: 'Forgot Password?',
      noAccount: "Don't have an account?",
      haveAccount: 'Already have an account?',
      signUpHere: 'Sign up here',
      signInHere: 'Sign in here',
      continueWith: 'Or continue with',
      registerWith: 'Or register with',
      socialLogin: 'Login with {provider}',
      socialRegister: 'Register with {provider}'
    },
    
    // Events
    events: {
      title: 'Events',
      subtitle: 'Discover the best events in your city. Filter, search and find your next unforgettable experience.',
      search: 'Search events...',
      found: 'found',
      createEvent: 'Create Event',
      editEvent: 'Edit Event',
      deleteEvent: 'Delete Event',
      eventTitle: 'Event Title',
      description: 'Description',
      date: 'Date',
      time: 'Time',
      location: 'Location',
      price: 'Price',
      capacity: 'Capacity',
      category: 'Category',
      image: 'Image',
      tags: 'Tags',
      status: 'Status',
      active: 'Active',
      inactive: 'Inactive',
      cancelled: 'Cancelled',
      featured: 'Featured Events',
      upcoming: 'Upcoming Events',
      past: 'Past Events',
      allEvents: 'All Events',
      noEvents: 'No events found',
      noEventsDescription: 'Try adjusting the filters or search with other terms.',
      createNewEvent: 'Create New Event',
      eventDetails: 'Event Details',
      participants: 'Participants',
      comments: 'Comments',
      reviews: 'Reviews',
      share: 'Share',
      save: 'Save',
      cancel: 'Cancel',
      delete: 'Delete',
      edit: 'Edit',
      view: 'View',
      join: 'Join',
      leave: 'Leave',
      full: 'Full',
      available: 'Available',
      soldOut: 'Sold Out'
    },
    
    // Suppliers
    suppliers: {
      title: 'Suppliers',
      createSupplier: 'Create Supplier',
      editSupplier: 'Edit Supplier',
      deleteSupplier: 'Delete Supplier',
      supplierName: 'Supplier Name',
      description: 'Description',
      services: 'Services',
      rating: 'Rating',
      reviews: 'Reviews',
      contact: 'Contact',
      website: 'Website',
      socialMedia: 'Social Media',
      portfolio: 'Portfolio',
      availability: 'Availability',
      pricing: 'Pricing',
      experience: 'Experience',
      specialties: 'Specialties',
      noSuppliers: 'No suppliers available',
      createNewSupplier: 'Create New Supplier',
      supplierDetails: 'Supplier Details',
      contactSupplier: 'Contact Supplier',
      hireSupplier: 'Hire Supplier',
      viewPortfolio: 'View Portfolio',
      addReview: 'Add Review',
      editReview: 'Edit Review',
      deleteReview: 'Delete Review'
    },
    
    // Dashboard
    dashboard: {
      title: 'Dashboard',
      welcome: 'Welcome',
      subtitle: 'Manage your events and suppliers from here',
      totalEvents: 'Total Events',
      totalUsers: 'Total Users',
      totalRevenue: 'Total Revenue',
      activeEvents: 'Active Events',
      thisMonth: 'This Month',
      activeUsers: 'Active Users',
      ongoing: 'Ongoing',
      recentActivity: 'Recent Activity',
      upcomingEvents: 'Upcoming Events',
      viewAll: 'View All',
      refresh: 'Refresh',
      filter: 'Filter',
      download: 'Download',
      share: 'Share',
      stats: 'Statistics',
      analytics: 'Analytics',
      reports: 'Reports',
      settings: 'Settings'
    },
    
    // Forms
    forms: {
      required: 'Required field',
      invalidEmail: 'Invalid email',
      passwordTooShort: 'Password must be at least 8 characters',
      passwordsDoNotMatch: 'Passwords do not match',
      invalidPhone: 'Invalid phone number',
      invalidDate: 'Invalid date',
      invalidTime: 'Invalid time',
      invalidPrice: 'Invalid price',
      invalidCapacity: 'Invalid capacity',
      fileTooLarge: 'File is too large',
      invalidFileType: 'Invalid file type',
      maxLength: 'Maximum {max} characters',
      minLength: 'Minimum {min} characters',
      selectOption: 'Select an option',
      uploadFile: 'Upload file',
      dragAndDrop: 'Drag and drop files here',
      or: 'or',
      browse: 'Browse',
      remove: 'Remove',
      save: 'Save',
      cancel: 'Cancel',
      submit: 'Submit',
      reset: 'Reset',
      loading: 'Loading...',
      saving: 'Saving...',
      success: 'Success!',
      error: 'Error',
      warning: 'Warning',
      info: 'Information'
    },
    
    // System messages
    messages: {
      success: {
        eventCreated: 'Event created successfully',
        eventUpdated: 'Event updated successfully',
        eventDeleted: 'Event deleted successfully',
        supplierCreated: 'Supplier created successfully',
        supplierUpdated: 'Supplier updated successfully',
        supplierDeleted: 'Supplier deleted successfully',
        userRegistered: 'User registered successfully',
        userLoggedIn: 'User logged in successfully',
        userLoggedOut: 'User logged out successfully',
        profileUpdated: 'Profile updated successfully',
        settingsSaved: 'Settings saved successfully',
        dataSaved: 'Data saved successfully'
      },
      error: {
        generic: 'An unexpected error occurred',
        network: 'Connection error. Check your internet.',
        unauthorized: 'You do not have permission to perform this action',
        forbidden: 'Access denied',
        notFound: 'Resource not found',
        validation: 'Invalid input data',
        server: 'Internal server error',
        loginFailed: 'Invalid credentials',
        registrationFailed: 'User registration failed',
        eventNotFound: 'Event not found',
        supplierNotFound: 'Supplier not found',
        userNotFound: 'User not found',
        fileUploadFailed: 'File upload failed',
        paymentFailed: 'Payment failed',
        emailSendFailed: 'Email send failed'
      },
      warning: {
        unsavedChanges: 'You have unsaved changes',
        confirmDelete: 'Are you sure you want to delete this item?',
        sessionExpired: 'Your session has expired',
        lowStorage: 'Low storage space',
        maintenanceMode: 'System is in maintenance mode'
      },
      info: {
        loading: 'Loading...',
        noData: 'No data available',
        searchResults: 'Search results',
        filtersApplied: 'Filters applied',
        dataUpdated: 'Data updated',
        newVersionAvailable: 'New version available'
      }
    },
    
    // Event categories
    categories: {
      concert: 'Concert',
      conference: 'Conference',
      workshop: 'Workshop',
      sport: 'Sport',
      art: 'Art',
      technology: 'Technology',
      business: 'Business',
      other: 'Other'
    },
    
    // Status
    status: {
      active: 'Active',
      inactive: 'Inactive',
      pending: 'Pending',
      approved: 'Approved',
      rejected: 'Rejected',
      cancelled: 'Cancelled',
      completed: 'Completed',
      draft: 'Draft',
      published: 'Published'
    },
    
    // Roles
    roles: {
      admin: 'Administrator',
      user: 'User',
      supplier: 'Supplier',
      moderator: 'Moderator'
    },
    
    // Dates and time
    time: {
      now: 'Now',
      today: 'Today',
      yesterday: 'Yesterday',
      tomorrow: 'Tomorrow',
      thisWeek: 'This Week',
      thisMonth: 'This Month',
      thisYear: 'This Year',
      lastWeek: 'Last Week',
      lastMonth: 'Last Month',
      lastYear: 'Last Year',
      nextWeek: 'Next Week',
      nextMonth: 'Next Month',
      nextYear: 'Next Year',
      monday: 'Monday',
      tuesday: 'Tuesday',
      wednesday: 'Wednesday',
      thursday: 'Thursday',
      friday: 'Friday',
      saturday: 'Saturday',
      sunday: 'Sunday',
      january: 'January',
      february: 'February',
      march: 'March',
      april: 'April',
      may: 'May',
      june: 'June',
      july: 'July',
      august: 'August',
      september: 'September',
      october: 'October',
      november: 'November',
      december: 'December'
    },
    
    // Settings
    settings: {
      title: 'Settings',
      general: 'General',
      profile: 'Profile',
      notifications: 'Notifications',
      privacy: 'Privacy',
      security: 'Security',
      language: 'Language',
      theme: 'Theme',
      timezone: 'Timezone',
      currency: 'Currency',
      dateFormat: 'Date Format',
      timeFormat: 'Time Format',
      emailNotifications: 'Email Notifications',
      pushNotifications: 'Push Notifications',
      smsNotifications: 'SMS Notifications',
      profileVisibility: 'Profile Visibility',
      showEmail: 'Show Email',
      showPhone: 'Show Phone',
      public: 'Public',
      private: 'Private',
      friends: 'Friends',
      save: 'Save',
      cancel: 'Cancel',
      reset: 'Reset',
      delete: 'Delete'
    }
  }
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(() => {
    // Prioridad: localStorage > navegador > español
    const stored = localStorage.getItem('language');
    if (stored && ['es', 'en'].includes(stored)) {
      return stored;
    }
    
    const browserLang = navigator.language.split('-')[0];
    return ['es', 'en'].includes(browserLang) ? browserLang : 'es';
  });

  // Guardar en localStorage
  useEffect(() => {
    localStorage.setItem('language', language);
  }, [language]);

  // Función de traducción con interpolación
  const t = (key, params = {}) => {
    const keys = key.split('.');
    
    // Combinar traducciones base con adicionales
    const combinedTranslations = {
      ...translations[language],
      ...additionalTranslations[language]
    };
    
    let value = combinedTranslations;
    
    for (const k of keys) {
      value = value?.[k];
    }
    
    if (!value) {
      console.warn(`❌ Translation missing for key: ${key} in language: ${language}`);
      return key;
    }
    
    // Interpolación de parámetros
    if (typeof value === 'string' && Object.keys(params).length > 0) {
      return value.replace(/\{(\w+)\}/g, (match, paramKey) => {
        return params[paramKey] || match;
      });
    }
    
    return value;
  };

  // Función para cambiar idioma
  const changeLanguage = (newLanguage) => {
    console.log('🔄 Changing language from', language, 'to', newLanguage);
    if (['es', 'en'].includes(newLanguage)) {
      setLanguage(newLanguage);
      console.log('✅ Language changed to:', newLanguage);
    } else {
      console.warn(`❌ Unsupported language: ${newLanguage}`);
    }
  };

  // Función para obtener idioma actual
  const getCurrentLanguage = () => language;

  // Función para obtener idiomas disponibles
  const getAvailableLanguages = () => [
    { code: 'es', name: 'Español', flag: '🇪🇸' },
    { code: 'en', name: 'English', flag: '🇺🇸' }
  ];

  // Función para formatear fechas según el idioma
  const formatDate = (date, options = {}) => {
    const defaultOptions = {
      year: 'numeric',
      month: 'long',
      day: 'numeric'
    };
    
    return new Intl.DateTimeFormat(language, { ...defaultOptions, ...options }).format(date);
  };

  // Función para formatear números según el idioma
  const formatNumber = (number, options = {}) => {
    return new Intl.NumberFormat(language, options).format(number);
  };

  // Función para formatear moneda según el idioma
  const formatCurrency = (amount, currency = 'USD') => {
    return new Intl.NumberFormat(language, {
      style: 'currency',
      currency: currency
    }).format(amount);
  };

  const value = {
    language,
    changeLanguage,
    getCurrentLanguage,
    getAvailableLanguages,
    t,
    formatDate,
    formatNumber,
    formatCurrency
  };

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
};

export default LanguageContext;
